# docke image MySQL e ADMINER
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minhasenhasegura
    ports:
      - "3306:3306"
    volumes:
      - "D:/docker-volumes/mysql/my.conf:/etc/mysql/conf.d/config-file.cnf" #"./my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "D:/docker-volumes/mysql/data:/var/lib/mysql:rw"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080